/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/buildings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Buildings */
        get: operations["list_buildings_api_v1_buildings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Complaints */
        get: operations["list_my_complaints_api_v1_complaints_get"];
        put?: never;
        /** Submit Complaint */
        post: operations["submit_complaint_api_v1_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints/{complaint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Complaint */
        get: operations["read_complaint_api_v1_complaints__complaint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/my-work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Work */
        get: operations["list_my_work_api_v1_incidents_my_work_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Incident */
        get: operations["read_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/manual-triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Triage Incident */
        post: operations["manual_triage_incident_api_v1_incidents__incident_id__manual_triage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/escalate-safety": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Escalate Safety Incident */
        post: operations["escalate_safety_incident_api_v1_incidents__incident_id__escalate_safety_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Incident Technician */
        post: operations["assign_incident_technician_api_v1_incidents__incident_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Incident */
        post: operations["start_incident_api_v1_incidents__incident_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Incident */
        post: operations["resolve_incident_api_v1_incidents__incident_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Resolved Incident */
        post: operations["close_resolved_incident_api_v1_incidents__incident_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Operations Metrics */
        get: operations["read_operations_metrics_api_v1_metrics_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ai Metrics */
        get: operations["read_ai_metrics_api_v1_metrics_ai_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Technicians */
        get: operations["list_technicians_api_v1_technicians_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check that intentionally avoids database access.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness check that verifies database connectivity.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveAssignmentSummary */
        ActiveAssignmentSummary: {
            /**
             * Assignment Id
             * Format: uuid
             */
            assignment_id: string;
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /** Technician Display Name */
            technician_display_name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "DECLINED";
        };
        /** AiMetricsResponse */
        AiMetricsResponse: {
            scope: components["schemas"]["MetricsScope"];
            /** Triage Requests */
            triage_requests: number;
            /** Successfully Processed Requests */
            successfully_processed_requests: number;
            /** Pending Requests */
            pending_requests: number;
            /** Failed Requests */
            failed_requests: number;
            /** Total Retry Attempts */
            total_retry_attempts: number;
            /** Requests With Retries */
            requests_with_retries: number;
            /** Persisted Successful Triage Results */
            persisted_successful_triage_results: number;
            /** Persisted Failed Triage Results */
            persisted_failed_triage_results: number;
            /** Incidents Awaiting Human Review */
            incidents_awaiting_human_review: number;
        };
        /** AssignmentCreateRequest */
        AssignmentCreateRequest: {
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /** Expected Version */
            expected_version: number;
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /**
             * Assignment Id
             * Format: uuid
             */
            assignment_id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "DECLINED";
            /**
             * Incident Status
             * @enum {string}
             */
            incident_status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /** Incident Version */
            incident_version: number;
        };
        /** AuthenticatedUserBuilding */
        AuthenticatedUserBuilding: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Timezone */
            timezone: string;
        };
        /** AuthenticatedUserResponse */
        AuthenticatedUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Role */
            role: string;
            /** Building Ids */
            building_ids: string[];
            /** Buildings */
            buildings: components["schemas"]["AuthenticatedUserBuilding"][];
        };
        /** BuildingListItem */
        BuildingListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string | null;
            /** Timezone */
            timezone: string;
        };
        /** BuildingListResponse */
        BuildingListResponse: {
            /** Items */
            items: components["schemas"]["BuildingListItem"][];
        };
        /** ComplaintCreateRequest */
        ComplaintCreateRequest: {
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Description */
            description: string;
        };
        /** ComplaintCreateResponse */
        ComplaintCreateResponse: {
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Status
             * @constant
             */
            status: "PENDING_TRIAGE";
        };
        /** ComplaintDetailResponse */
        ComplaintDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Reporter Display Name */
            reporter_display_name: string;
            /** Description */
            description: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "MANUAL_REVIEW" | "CLOSED";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            incident: components["schemas"]["IncidentSummary"];
            /** Ai Safety Notes */
            ai_safety_notes?: string[];
        };
        /** ComplaintTriageExtraction */
        ComplaintTriageExtraction: {
            /**
             * Category
             * @enum {string}
             */
            category: "PLUMBING" | "ELECTRICAL" | "HVAC" | "STRUCTURAL" | "CLEANING" | "SECURITY" | "GENERAL" | "UNKNOWN";
            /** Location */
            location: string | null;
            /** Issue Summary */
            issue_summary: string;
            /** Symptoms */
            symptoms: string[];
            /** Potential Hazards */
            potential_hazards: string[];
            /**
             * Suggested Priority
             * @enum {string}
             */
            suggested_priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Missing Information */
            missing_information: string[];
            /** Needs Human Review */
            needs_human_review: boolean;
            /** Safety Notes */
            safety_notes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Reporter Display Name */
            reporter_display_name: string;
            /** Complaint Description */
            complaint_description: string;
            /** Category */
            category: string | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /** Sla Deadline */
            sla_deadline: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Ai Triage Status */
            ai_triage_status?: string | null;
            latest_triage_result?: components["schemas"]["LatestTriageResultResponse"] | null;
            /** Ai Safety Notes */
            ai_safety_notes?: string[];
            active_assignment?: components["schemas"]["ActiveAssignmentSummary"] | null;
            safety_escalation?: components["schemas"]["SafetyEscalationSummary"] | null;
        };
        /** IncidentLifecycleRequest */
        IncidentLifecycleRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** IncidentListItem */
        IncidentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Complaint Description */
            complaint_description: string;
            /** Category */
            category: string | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ai Triage Status */
            ai_triage_status?: string | null;
            latest_triage_result?: components["schemas"]["LatestTriageResultResponse"] | null;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** IncidentResolveRequest */
        IncidentResolveRequest: {
            /** Expected Version */
            expected_version: number;
            /** Resolution Notes */
            resolution_notes: string;
        };
        /** IncidentSummary */
        IncidentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Category */
            category: string | null;
            /** Sla Deadline */
            sla_deadline: string | null;
            /** Version */
            version: number;
        };
        /** LatestTriageResultResponse */
        LatestTriageResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Model Version */
            model_version: string | null;
            validated_result: components["schemas"]["ComplaintTriageExtraction"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["AuthenticatedUserResponse"];
            /** Csrf Token */
            csrf_token: string;
            /**
             * Token Type
             * @default cookie
             */
            token_type: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /** ManualTriageRequest */
        ManualTriageRequest: {
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Expected Version */
            expected_version: number;
            /**
             * Suspected Hazard
             * @default false
             */
            suspected_hazard: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** MetricsScope */
        MetricsScope: {
            /** Building Id */
            building_id: string | null;
            /** Building Ids */
            building_ids: string[];
        };
        /** OperationsMetricsResponse */
        OperationsMetricsResponse: {
            scope: components["schemas"]["MetricsScope"];
            /** Total Incidents */
            total_incidents: number;
            /** Open Incidents */
            open_incidents: number;
            /** Pending Triage */
            pending_triage: number;
            /** Awaiting Assignment */
            awaiting_assignment: number;
            /** Assigned */
            assigned: number;
            /** In Progress */
            in_progress: number;
            /** Resolved */
            resolved: number;
            /** Closed */
            closed: number;
            /** Active Technician Assignments */
            active_technician_assignments: number;
            /** Available Technicians */
            available_technicians: number;
        };
        /** ReporterComplaintListItem */
        ReporterComplaintListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Description */
            description: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "MANUAL_REVIEW" | "CLOSED";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Incident Status
             * @enum {string}
             */
            incident_status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /** Incident Category */
            incident_category: string | null;
            /**
             * Incident Priority
             * @enum {string}
             */
            incident_priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        };
        /** ReporterComplaintListResponse */
        ReporterComplaintListResponse: {
            /** Items */
            items: components["schemas"]["ReporterComplaintListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** SafetyEscalationRequest */
        SafetyEscalationRequest: {
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
        };
        /** SafetyEscalationSummary */
        SafetyEscalationSummary: {
            /**
             * Actor Id
             * Format: uuid
             */
            actor_id: string;
            /** Actor Display Name */
            actor_display_name: string;
            /**
             * Escalated At
             * Format: date-time
             */
            escalated_at: string;
            /** Reason */
            reason: string;
        };
        /** TechnicianListItem */
        TechnicianListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Display Name */
            display_name: string;
            /** Skills */
            skills: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** Available */
            available: boolean;
            /** Active Assignment Id */
            active_assignment_id?: string | null;
        };
        /** TechnicianListResponse */
        TechnicianListResponse: {
            /** Items */
            items: components["schemas"]["TechnicianListItem"][];
        };
        /** TechnicianWorkItem */
        TechnicianWorkItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /** Public Ticket Id */
            public_ticket_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Complaint Description */
            complaint_description: string;
            /** Category */
            category: string | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED";
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Assignment Id
             * Format: uuid
             */
            assignment_id: string;
            /**
             * Assignment Status
             * @enum {string}
             */
            assignment_status: "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "DECLINED";
        };
        /** TechnicianWorkListResponse */
        TechnicianWorkListResponse: {
            /** Items */
            items: components["schemas"]["TechnicianWorkItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthenticatedUserResponse"];
                };
            };
        };
    };
    list_buildings_api_v1_buildings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BuildingListResponse"];
                };
            };
        };
    };
    list_my_complaints_api_v1_complaints_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReporterComplaintListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_complaint_api_v1_complaints_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_complaint_api_v1_complaints__complaint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW" | "SAFETY_ESCALATED") | null;
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_work_api_v1_incidents_my_work_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianWorkListResponse"];
                };
            };
        };
    };
    read_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_triage_incident_api_v1_incidents__incident_id__manual_triage_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualTriageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_safety_incident_api_v1_incidents__incident_id__escalate_safety_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SafetyEscalationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_incident_technician_api_v1_incidents__incident_id__assign_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_incident_api_v1_incidents__incident_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentLifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_incident_api_v1_incidents__incident_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_resolved_incident_api_v1_incidents__incident_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentLifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_operations_metrics_api_v1_metrics_operations_get: {
        parameters: {
            query?: {
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ai_metrics_api_v1_metrics_ai_get: {
        parameters: {
            query?: {
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiMetricsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_technicians_api_v1_technicians_get: {
        parameters: {
            query?: {
                building_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
