/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Complaint */
        post: operations["submit_complaint_api_v1_complaints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/complaints/{complaint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Complaint */
        get: operations["read_complaint_api_v1_complaints__complaint_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Incidents */
        get: operations["list_incidents_api_v1_incidents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Incident */
        get: operations["read_incident_api_v1_incidents__incident_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/manual-triage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Manual Triage Incident */
        post: operations["manual_triage_incident_api_v1_incidents__incident_id__manual_triage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Incident Technician */
        post: operations["assign_incident_technician_api_v1_incidents__incident_id__assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Incident */
        post: operations["start_incident_api_v1_incidents__incident_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Incident */
        post: operations["resolve_incident_api_v1_incidents__incident_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidents/{incident_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Resolved Incident */
        post: operations["close_resolved_incident_api_v1_incidents__incident_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Technicians */
        get: operations["list_technicians_api_v1_technicians_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness check that intentionally avoids database access.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description Readiness check that verifies database connectivity.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignmentCreateRequest */
        AssignmentCreateRequest: {
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /** Expected Version */
            expected_version: number;
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /**
             * Assignment Id
             * Format: uuid
             */
            assignment_id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Technician Id
             * Format: uuid
             */
            technician_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ASSIGNED" | "IN_PROGRESS" | "COMPLETED" | "CANCELLED" | "DECLINED";
            /**
             * Incident Status
             * @enum {string}
             */
            incident_status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW";
            /** Incident Version */
            incident_version: number;
        };
        /** ComplaintCreateRequest */
        ComplaintCreateRequest: {
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Description */
            description: string;
        };
        /** ComplaintCreateResponse */
        ComplaintCreateResponse: {
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /**
             * Incident Id
             * Format: uuid
             */
            incident_id: string;
            /**
             * Status
             * @constant
             */
            status: "PENDING_TRIAGE";
        };
        /** ComplaintDetailResponse */
        ComplaintDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Description */
            description: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "MANUAL_REVIEW" | "CLOSED";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            incident: components["schemas"]["IncidentSummary"];
        };
        /** ComplaintTriageExtraction */
        ComplaintTriageExtraction: {
            /**
             * Category
             * @enum {string}
             */
            category: "PLUMBING" | "ELECTRICAL" | "HVAC" | "STRUCTURAL" | "CLEANING" | "SECURITY" | "GENERAL" | "UNKNOWN";
            /** Location */
            location: string | null;
            /** Issue Summary */
            issue_summary: string;
            /** Symptoms */
            symptoms: string[];
            /** Potential Hazards */
            potential_hazards: string[];
            /**
             * Suggested Priority
             * @enum {string}
             */
            suggested_priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Missing Information */
            missing_information: string[];
            /** Needs Human Review */
            needs_human_review: boolean;
            /** Safety Notes */
            safety_notes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IncidentDetailResponse */
        IncidentDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /**
             * Reporter Id
             * Format: uuid
             */
            reporter_id: string;
            /** Complaint Description */
            complaint_description: string;
            /** Category */
            category: string | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW";
            /** Sla Deadline */
            sla_deadline: string | null;
            /** Version */
            version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Ai Triage Status */
            ai_triage_status?: string | null;
            latest_triage_result?: components["schemas"]["LatestTriageResultResponse"] | null;
        };
        /** IncidentLifecycleRequest */
        IncidentLifecycleRequest: {
            /** Expected Version */
            expected_version: number;
        };
        /** IncidentListItem */
        IncidentListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Complaint Id
             * Format: uuid
             */
            complaint_id: string;
            /**
             * Building Id
             * Format: uuid
             */
            building_id: string;
            /** Complaint Description */
            complaint_description: string;
            /** Category */
            category: string | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Ai Triage Status */
            ai_triage_status?: string | null;
            latest_triage_result?: components["schemas"]["LatestTriageResultResponse"] | null;
        };
        /** IncidentListResponse */
        IncidentListResponse: {
            /** Items */
            items: components["schemas"]["IncidentListItem"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** IncidentResolveRequest */
        IncidentResolveRequest: {
            /** Expected Version */
            expected_version: number;
            /** Resolution Notes */
            resolution_notes: string;
        };
        /** IncidentSummary */
        IncidentSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW";
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Category */
            category: string | null;
            /** Sla Deadline */
            sla_deadline: string | null;
            /** Version */
            version: number;
        };
        /** LatestTriageResultResponse */
        LatestTriageResultResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Status */
            status: string;
            /** Model Version */
            model_version: string | null;
            validated_result: components["schemas"]["ComplaintTriageExtraction"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ManualTriageRequest */
        ManualTriageRequest: {
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
            /** Expected Version */
            expected_version: number;
            /**
             * Suspected Hazard
             * @default false
             */
            suspected_hazard: boolean;
            /** Notes */
            notes?: string | null;
        };
        /** TechnicianListItem */
        TechnicianListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Display Name */
            display_name: string;
            /** Skills */
            skills: string[];
            /**
             * Status
             * @enum {string}
             */
            status: "ACTIVE" | "INACTIVE";
            /** Available */
            available: boolean;
            /** Active Assignment Id */
            active_assignment_id?: string | null;
        };
        /** TechnicianListResponse */
        TechnicianListResponse: {
            /** Items */
            items: components["schemas"]["TechnicianListItem"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submit_complaint_api_v1_complaints_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_complaint_api_v1_complaints__complaint_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                complaint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_incidents_api_v1_incidents_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("PENDING_TRIAGE" | "AWAITING_ASSIGNMENT" | "AWAITING_APPROVAL" | "ASSIGNED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | "MANUAL_REVIEW") | null;
            };
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_incident_api_v1_incidents__incident_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    manual_triage_incident_api_v1_incidents__incident_id__manual_triage_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualTriageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_incident_technician_api_v1_incidents__incident_id__assign_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_incident_api_v1_incidents__incident_id__start_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentLifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_incident_api_v1_incidents__incident_id__resolve_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_resolved_incident_api_v1_incidents__incident_id__close_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path: {
                incident_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IncidentLifecycleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IncidentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_technicians_api_v1_technicians_get: {
        parameters: {
            query?: never;
            header?: {
                "X-Dev-User-Id"?: string | null;
                "X-Dev-Role"?: string | null;
                "X-Dev-Building-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TechnicianListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
